### ISSUE TITLE
Error: example.dot: syntax error in line 25 near '.'

### ISSUE THREAD

**Issue by kirill3000** [ehne/ERDot#4]
Hello if i change table name "Perggon" to "Perg.gon" i have a error

Error: example.dot: syntax error in line 25 near '.'

line 25 in example.dot
Perg.gon [ label=<

part of my example.erd.json

"tables": {
		"Perg.gon": {
			"*name": "char()",
			"height": "int()",
			"weight": "int()",
			"birthDate": "date()",
			"+birthPlaceID": "int()"
		}
		
	}

name of table can be  different  , could you add quote character ?
    "Perg.gon" [ label=<
thank you

**Comment by ehne** [comment]
hello,

thank you for taking the time to write a bug report.

your suggestion of using quotation marks should work, I will try and code it up now.

-ehne

**Comment by ehne** [comment]
hello, version 2.1.5 should fix this behaviour, thanks again for letting me know
