### ISSUE TITLE
Alternative key designation?

### ISSUE THREAD

**Issue by SeaDude** [ehne/ERDot#6]
Hello,

(Still new to data modeling and ER diagramming)

In the README [table](https://github.com/ehne/ERDot#table) section, when you say...

> You can combine two of these together into a primary foreign key, just by putting both a * and a + next to the name

...is this the same visual representation as designating an "Alternative Key"?

Thank you

**Comment by ehne** [comment]
Hello,

I don't think it would be an [alternative key](https://en.wikipedia.org/w/index.php?title=Alternate_key&redirect=no) (if we're saying that an alternative key is "a candidate key that is not the primary key.").

A primary foreign key is more like a [compound key](https://en.wikipedia.org/wiki/Composite_key), in that each of its component keys are foreign, but it works as a primary key.

A primary use case for this kind of key is a table to join two other tables together

<img width="464" alt="Screen Shot 2021-04-25 at 9 14 01 am" src="https://user-images.githubusercontent.com/7551957/115975267-97828680-a5a6-11eb-80f6-8d6fc0ca9d60.png">

So this would allow for a user to have multiple roles.

Hopefully this helps explain what the term primary foreign key means.

-ehne

**Comment by SeaDude** [comment]
You explain it well. Thank you.
